plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.javamodularity.moduleplugin' version '1.8.15'
}

group = 'ru.sharphurt'
version = '0.0.1-SNAPSHOT'
description = 'music-server'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation project(':app:api')
    implementation project(':app:common')
    implementation project(':app:mediametadata')
    implementation project(':app:musicserver')
    implementation project(':app:soulseek')
    implementation project(':app:user')

    implementation 'org.springframework.boot:spring-boot-starter'
}

allprojects {
    repositories {
        mavenCentral()
        maven { url 'https://spring.io' }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.javamodularity.moduleplugin'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << '-parameters'
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.6"
        }
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
