services:
    app:
        container_name: music-search-app
        build: .
        ports:
            - "8090:8080"
        environment:
            SPRING_PROFILES_ACTIVE: dev
            SLSKD_BASE_URL: ${SLSKD_BASE_URL}
            SLSKD_SECRET_API_KEY: ${SLSKD_SECRET_API_KEY}
            SLSKD_COMPLETE_DIR: ${SLSKD_COMPLETE_DIR}
            SLSKD_INCOMPLETE_DIR: ${SLSKD_INCOMPLETE_DIR}
            SERVER_BASE_URL: ${SERVER_BASE_URL}
            JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
        depends_on:
            - postgres
        volumes:
            - ${MUSIC_DIR}:${MUSIC_DIR}
        restart: unless-stopped

    postgres:
        image: postgres:17-alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: musicserver
        ports:
            - "5433:5432"

networks:
    default:
        name: music-network
        external: true