services:
  postgres:
    image: postgres:14.18
    environment:
      POSTGRES_USER: u1
      POSTGRES_PASSWORD: p1
      POSTGRES_DB: HOLD
    ports:
      - "5452:5432"
    volumes:
      - ./docker/target-hold-db:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    restart: unless-stopped