plugins {
    id 'java-library'
}

dependencies {
    implementation project(':app:common')
    implementation project(':app:soulseek')
    implementation project(':app:user')
    implementation project(':app:musicserver')
    implementation project(':app:mediametadata')

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-cache'

    implementation 'com.fasterxml.jackson.core:jackson-databind'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}