spring:
    datasource:
        url: ${POSTGRES_HOST:jdbc:postgresql://localhost:5433/musicserver}
        username: ${POSTGRES_USER:sharphurt}
        password: ${POSTGRES_PASSWORD:password}
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: true

    cache:
        type: caffeine
        caffeine:
            spec: maximumSize=500,expireAfterWrite=10m

    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

slskd:
    url: ${SLSKD_BASE_URL:http://localhost:5030}
    api-key: ${SLSKD_SECRET_API_KEY:SuperSecretKey123456789!}
    host-base-path: ${SLSKD_APP_DIR:/home/username/slskd}
#    complete-dir: ${SLSKD_COMPLETE_DIR:/home/username/music/downloads}
#    incomplete-dir: ${SLSKD_INCOMPLETE_DIR:/home/username/music/incomplete}

library:
    base-dir: ${LIBRARY_BASE_DIR:/home/username/music/library}

server-base-url: ${SERVER_BASE_URL:http://localhost:8080}

logging:
    level:
        ru.sharphurt.musicserver: info
