#file: noinspection YAMLSchemaValidation
spring:
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}

lastfm:
  url: https://ws.audioscrobbler.com/2.0
  image-base-url: https://lastfm.freetls.fastly.net


slskd:
  url: ${SLSKD_BASE_URL:http://localhost:5030}
  api-key: ${SLSKD_SECRET_API_KEY:SuperSecretKey123456789!}

server-base-url: ${SERVER_BASE_URL:http://localhost:8080}

logging:
  level:
    ru.sharphurt.musicserver: info
